### ISSUE TITLE
雷电三接口插拔就死机

### ISSUE THREAD

**Issue by yukino521** [mikeTOliu/dell-latitude7370-Hackintosh-EFI-backup#2]
雷电三接口插拔任何设备都会死机，包括充电，不知道我是不是个例。。

**Comment by mikeTOliu** [comment]
我没有这种情况，但是雷电三不支持热插拔，你可以试试替换usb驱动

**Comment by mikeTOliu** [comment]
无法热插拔只是usbc口数据不可用，但不影响充电

**Comment by yukino521** [comment]
> 无法热插拔只是usbc口数据不可用，但不影响充电
emmm，也可能是我解压缩文件出问题了，还有个EFI压缩包是做什么用的？clover文件夹下还有个config的压缩包，要用哪个呢？

**Comment by yukino521** [comment]
还是说BIOS需要特殊设置呢，我只改了dvmt显存

**Comment by mikeTOliu** [comment]
那个efi的压缩包是我为了方便下载弄的，config是我之前备份的配置文件用文件夹里的新的就行，你装的mac版本是多少？

**Comment by yukino521** [comment]
装的10.14.6

**Comment by yukino521** [comment]
兄弟，你的bios版本是多少

**Comment by mikeTOliu** [comment]
01.04.05

**Comment by yukino521** [comment]
放弃了，bios降级会失败，我已经是最新版BIOS了
